# Основные настройки
title: Мой Тестовый Сайт
email: your-email@example.com
description: >- # Описание сайта
  Здесь я тестирую Jekyll перед запуском основного сайта игры.

# Настройки путей (Самое важное!)
baseurl: "/test-jekyll" # ВАЖНО: Название вашего репозитория со слэшем в начале
url: "https://niamonty.github.io" # Ваш технический адрес GitHub

# Сборка
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock