# Основные настройки
title: Мой Тестовый Сайт
email: your-email@example.com
description: >- # Описание сайта
  ХАХАХАХХ

# Настройки путей
baseurl: "/tm_site"
url: "https://niamonty.github.io"

# Сборка
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock