# Основные настройки
title: Мой Тестовый Сайт
email: your-email@example.com
description: >- # Описание сайта
  ХАХАХАХХ

# Настройки путей
baseurl: ""
url: "https://tendymesh.com"

# Сборка
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock